stages:
 -  build
 -  test
 -  sonarqube

build:
  stage: build
  script:
    - cd JavaProject\Sem3Individual
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
 stage: test
 script:
   - cd JavaProject\Sem3Individual
   - ./gradlew test
   - ./gradlew.bat --stop

sonarqube-check:
  stage: sonarqube
  script:
    - cd JavaProject\Sem3Individual
    - ./gradlew sonarqube -D'sonar.qualitygate.wait=true'
    - ./gradlew.bat --stop
  allow_failure: true
  only:
    - master
    - merge_request