stages:
 -  build
 -  test

build:
  stage: build
  script:
    - cd JavaProject\Sem3Individual
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
 stage: test
 script:
   - cd JavaProject\Sem3Individual
   - ./gradlew test
   - ./gradlew.bat --stop

after script:
  script:
    - echo "End of ci"