version: "3"
services:
  sem3yugiohfrontend:
    build: ./front-end-indiv-app
    ports:
      - 3000:3000
    depends_on:
      - "sem3yugiohbackend"
      
  sem3yugiohdb:
    container_name: sem3yugiohdb
    ports:
      - 3306:3306
    image: mysql:latest
    volumes:
      - yugioh:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 333lollpop
      MYSQL_DATABASE: sem3yugioh
      
  sem3yugiohbackend:
    build: ./JavaProject/Sem3Individual
    ports:
      - 8080:8080
    depends_on:
      - "sem3yugiohdb"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://sem3yugiohdb:3306/sem3yugioh?enabledTLSProtocols=TLSv1.2",
        "spring.datasource.username": "root",
        "spring.datasource.password": "333lollpop",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"
        }'
    
volumes:
    yugioh: